[package]
name = "buildwars"
version = "0.3.1"
edition = "2021"

[dependencies]
itertools = "0.12.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gw2lib]
version = "3.0.0"
features = ["blocking"]
